

name: Deploy React App to AWS S3 using Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - env:
          CI: false
      - run: npm install
      - run: npm run build
      
      

    
     
